---
- name: web-server configuration
  hosts: web
  become: yes

  roles:
   - common
   - webserver
   - security

- name: build configuration
  hosts: build
  become: yes

  roles:
   - common
   - security
