---
# tasks file for security
- name: Copy banner
  copy: src=banner dest=/etc/ssh/

- name: Edit config
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'Banner /etc/ssh/banner'
  notify: 
    - restart sshd
