---
# tasks file for webserver
- name: Ensure tomcat is present
  apt: name=tomcat9 state=present

- name: Copy war file from local to web host
  copy: src={{ src }}/*.war dest={{ dest }}/hello-1.0.war
  notify:
   -  restart tomcat9
